filter:
  dependency_paths:
    - vendor/
    - vendors/
    - woocommerce/
    - woocommerce/packages/woocommerce-blocks/src/
    - wordpress/
  excluded_paths:
    - assets/
    - languages/
    - node_modules/
    - tests/

build:
  dependencies:
    override: true
  nodes:
    analysis:
      cache:
        disabled: false
        directories:
          - ~/.composer/cache
      dependencies:
        before:
          - composer config --no-plugins allow-plugins.composer/installers true
          - composer config --no-plugins allow-plugins.johnpbloch/wordpress-core-installer true
          - composer require --dev johnpbloch/wordpress
          - composer require --dev woocommerce/woocommerce
      environment:
        node: false
        php: '7.4'
      services:
        mysql: '5.7'
      project_setup:
        override: true
        before:
          - bash tests/bin/install.sh wordpress_test root "" 127.0.0.1:3306 $WP_VERSION
      tests:
        override:
          - jshint-run
          - php-scrutinizer-run --enable-security-analysis
          -
            command: vendor/bin/phpunit --coverage-clover=tests/coverage/clover.xml
            coverage:
              file: tests/coverage/clover.xml
              format: clover

tools:
  php_code_sniffer:
    config:
      standard: WordPress
  sensiolabs_security_checker: true

checks:
  php:
    no_exit: false
    simplify_boolean_return: true
    check_method_contracts:
      verify_interface_like_constraints: true
      verify_documented_constraints: true
      verify_parent_constraints: true
    return_doc_comments: true
    return_doc_comment_if_not_inferrable: true
  javascript:
    no_else_return: true
    eqeqeq: true
