<?php

return [
	'settings.general.require.approval' => [
		'default' => 'no',
		'description' => __( 'Set the status of new review submissions to pending.', 'site-reviews' ),
		'label' => __( 'Require approval', 'site-reviews' ),
		'type' => 'yes_no',
	],
	'settings.general.require.login' => [
		'default' => 'no',
		'description' => __( 'Only allow review submissions from registered users.', 'site-reviews' ),
		'label' => __( 'Require login', 'site-reviews' ),
		'type' => 'yes_no',
	],
	'settings.general.require.login_register' => [
		'default' => 'no',
		'depends_on' => ['settings.general.require.login' => 'yes'],
		'description' => sprintf( __( 'Show a link for a new user to register. The %s Membership option must be enabled in General Settings for this to work.', 'site-reviews' ),
			'<a href="'.admin_url( 'options-general.php#users_can_register' ).'">'.__( 'Anyone can register', 'site-reviews' ).'</a>'
		),
		'label' => __( 'Show registration link', 'site-reviews' ),
		'type' => 'yes_no',
	],
	'settings.general.notification' => [
		'default' => 'none',
		'label' => __( 'Notifications', 'site-reviews' ),
		'options' => [
			'none' => __( 'Do not send review notifications', 'site-reviews' ),
			'default' => __( 'Send to administrator', 'site-reviews' ).' <code>'.(string)get_option( 'admin_email' ).'</code>',
			'custom' => __( 'Send to one or more email addresses', 'site-reviews' ),
			'webhook' => __( 'Send to <a href="https://slack.com/">Slack</a>', 'site-reviews' ),
		],
		'type' => 'radio',
	],
	'settings.general.notification_email' => [
		'default' => '',
		'depends_on' => ['settings.general.notification' => 'custom'],
		'label' => __( 'Send notification emails to', 'site-reviews' ),
		'placeholder' => __( 'Separate multiple emails with a comma', 'site-reviews' ),
		'type' => 'text',
	],
	'settings.general.webhook_url' => [
		'default' => '',
		'depends_on' => ['settings.general.notification' => 'webhook'],
		'description' => sprintf( __( 'To send notifications to Slack, create a new %s and then paste the provided Webhook URL in the field above.', 'site-reviews' ),
			'<a href="https://api.slack.com/incoming-webhooks">'.__( 'Incoming WebHook', 'site-reviews' ).'</a>'
		),
		'label' => __( 'Webhook URL', 'site-reviews' ),
		'type' => 'url',
	],
	'settings.general.notification_message' => [
		'default' => glsr( 'Modules\Html' )->buildTemplate( 'templates/email-notification' ),
		'depends_on' => ['settings.general.notification' => ['custom', 'default', 'webhook']],
		'description' => __(
			'To restore the default text, save an empty template. '.
			'If you are sending notifications to Slack then this template will only be used as a fallback in the event that <a href="https://api.slack.com/docs/attachments">Message Attachments</a> have been disabled. Available template tags:'.
			'<br><code>{review_rating}</code> The review rating number (1-5)'.
			'<br><code>{review_title}</code> The review title'.
			'<br><code>{review_content}</code> The review content'.
			'<br><code>{review_author}</code> The review author'.
			'<br><code>{review_email}</code> The email of the review author'.
			'<br><code>{review_ip}</code> The IP address of the review author'.
			'<br><code>{review_link}</code> The link to edit/view a review',
			'site-reviews'
		),
		'label' => __( 'Notification template', 'site-reviews' ),
		'rows' => 10,
		'type' => 'code',
	],
	'settings.reviews.date.format' => [
		'default' => '',
		'description' => sprintf( __( 'The default date format is the one set in your %s.', 'site-reviews' ),
			'<a href="'.admin_url( 'options-general.php#date_format_custom' ).'">'.__( 'WordPress settings', 'site-reviews' ).'</a>'
		),
		'label' => __( 'Date Format', 'site-reviews' ),
		'options' => [
			'' => __( 'Use the default date format', 'site-reviews' ),
			'relative' => __( 'Use a relative date format', 'site-reviews' ),
			'custom' => __( 'Use a custom date format', 'site-reviews' ),
		],
		'type' => 'select',
	],
	'settings.reviews.date.custom' => [
		'default' => get_option( 'date_format' ),
		'depends_on' => ['settings.reviews.date.format' => 'custom'],
		'description' => __( 'Enter a custom date format (<a href="https://codex.wordpress.org/Formatting_Date_and_Time">documentation on date and time formatting</a>).', 'site-reviews' ),
		'label' => __( 'Custom Date Format', 'site-reviews' ),
		'type' => 'text',
	],
	'settings.reviews.assigned_links.enabled' => [
		'default' => 'no',
		'description' => __( 'Display a link to the assigned post of a review.', 'site-reviews' ),
		'label' => __( 'Enable Assigned Links', 'site-reviews' ),
		'type' => 'yes_no',
	],
	'settings.reviews.avatars.enabled' => [
		'default' => 'no',
		'description' => __( 'Display reviewer avatars. These are generated from the email address of the reviewer using <a href="https://gravatar.com">Gravatar</a>.', 'site-reviews' ),
		'label' => __( 'Enable Avatars', 'site-reviews' ),
		'type' => 'yes_no',
	],
	'settings.reviews.avatars.regenerate' => [
		'default' => 'no',
		'depends_on' => ['settings.reviews.avatars.enabled' => 'yes'],
		'description' => __( 'Regenerate the avatar whenever a local review is shown?', 'site-reviews' ),
		'label' => __( 'Regenerate Avatars', 'site-reviews' ),
		'type' => 'yes_no',
	],
	'settings.reviews.avatars.size' => [
		'default' => 40,
		'depends_on' => ['settings.reviews.avatars.enabled' => 'yes'],
		'description' => __( 'Set the avatar size in pixels.', 'site-reviews' ),
		'label' => __( 'Avatar Size', 'site-reviews' ),
		'type' => 'number',
	],
	'settings.reviews.excerpt.enabled' => [
		'default' => 'no',
		'description' => __( 'Display an excerpt instead of the full review.', 'site-reviews' ),
		'label' => __( 'Enable Excerpts', 'site-reviews' ),
		'type' => 'yes_no',
	],
	'settings.reviews.excerpt.length' => [
		'default' => 55,
		'depends_on' => ['settings.reviews.excerpt.enabled' => 'yes'],
		'description' => __( 'Set the excerpt word length.', 'site-reviews' ),
		'label' => __( 'Excerpt Length', 'site-reviews' ),
		'type' => 'number',
	],
	'settings.schema.type.default' => [
		'default' => 'LocalBusiness',
		'description' => __( 'Custom Field name: <code>schema_type</code>', 'site-reviews' ),
		'label' => __( 'Default Schema Type', 'site-reviews' ),
		'options' => [
			'LocalBusiness' => __( 'Local Business', 'site-reviews' ),
			'Product' => __( 'Product', 'site-reviews' ),
			'custom' => __( 'Custom', 'site-reviews' ),
		],
		'type' => 'select',
	],
	'settings.schema.type.custom' => [
		'default' => '',
		'depends_on' => ['settings.schema.type.default' => 'custom'],
		'description' => '<a href="https://schema.org/docs/schemas.html">'.__( 'View more information on schema types here', 'site-reviews' ).'</a>',
		'label' => __( 'Custom Schema Type', 'site-reviews' ),
		'type' => 'text',
	],
	'settings.schema.name.default' => [
		'default' => 'post',
		'description' => __( 'Custom Field name: <code>schema_name</code>', 'site-reviews' ),
		'label' => __( 'Default Name', 'site-reviews' ),
		'options' => [
			'post' => __( 'Use the assigned or current page title', 'site-reviews' ),
			'custom' => __( 'Enter a custom title', 'site-reviews' ),
		],
		'type' => 'select',
	],
	'settings.schema.name.custom' => [
		'default' => '',
		'depends_on' => ['settings.schema.name.default' => 'custom'],
		'label' => __( 'Custom Name', 'site-reviews' ),
		'type' => 'text',
	],
	'settings.schema.description.default' => [
		'default' => 'post',
		'description' => __( 'Custom Field name: <code>schema_description</code>', 'site-reviews' ),
		'label' => __( 'Default Description', 'site-reviews' ),
		'options' => [
			'post' => __( 'Use the assigned or current page excerpt', 'site-reviews' ),
			'custom' => __( 'Enter a custom description', 'site-reviews' ),
		],
		'type' => 'select',
	],
	'settings.schema.description.custom' => [
		'default' => '',
		'depends_on' => ['settings.schema.description.default' => 'custom'],
		'label' => __( 'Custom Description', 'site-reviews' ),
		'type' => 'text',
	],
	'settings.schema.url.default' => [
		'default' => 'post',
		'description' => __( 'Custom Field name: <code>schema_url</code>', 'site-reviews' ),
		'label' => __( 'Default URL', 'site-reviews' ),
		'options' => [
			'post' => __( 'Use the assigned or current page URL', 'site-reviews' ),
			'custom' => __( 'Enter a custom URL', 'site-reviews' ),
		],
		'type' => 'select',
	],
	'settings.schema.url.custom' => [
		'default' => '',
		'depends_on' => ['settings.schema.url.default' => 'custom'],
		'label' => __( 'Custom URL', 'site-reviews' ),
		'type' => 'text',
	],
	'settings.schema.image.default' => [
		'default' => 'post',
		'description' => __( 'Custom Field name: <code>schema_image</code>', 'site-reviews' ),
		'label' => __( 'Default Image', 'site-reviews' ),
		'options' => [
			'post' => __( 'Use the featured image of the assigned or current page', 'site-reviews' ),
			'custom' => __( 'Enter a custom image URL', 'site-reviews' ),
		],
		'type' => 'select',
	],
	'settings.schema.image.custom' => [
		'default' => '',
		'depends_on' => ['settings.schema.image.default' => 'custom'],
		'label' => __( 'Custom Image URL', 'site-reviews' ),
		'type' => 'text',
	],
	'settings.schema.address' => [
		'default' => '',
		'depends_on' => ['settings.schema.type.default' => 'LocalBusiness'],
		'description' => __( 'Custom Field name: <code>schema_address</code>', 'site-reviews' ),
		'label' => __( 'Address', 'site-reviews' ),
		'placeholder' => '60 29th Street #343, San Francisco, CA 94110, US',
		'type' => 'text',
	],
	'settings.schema.telephone' => [
		'default' => '',
		'depends_on' => ['settings.schema.type.default' => 'LocalBusiness'],
		'description' => __( 'Custom Field name: <code>schema_telephone</code>', 'site-reviews' ),
		'label' => __( 'Telephone Number', 'site-reviews' ),
		'placeholder' => '+1 (877) 273-3049',
		'type' => 'text',
	],
	'settings.schema.pricerange' => [
		'default' => '',
		'depends_on' => ['settings.schema.type.default' => 'LocalBusiness'],
		'description' => __( 'Custom Field name: <code>schema_pricerange</code>', 'site-reviews' ),
		'label' => __( 'Price Range', 'site-reviews' ),
		'placeholder' => '$$-$$$',
		'type' => 'text',
	],
	'settings.schema.lowprice' => [
		'default' => '',
		'depends_on' => ['settings.schema.type.default' => 'Product'],
		'description' => __( 'Custom Field name: <code>schema_lowprice</code>', 'site-reviews' ),
		'label' => __( 'Low Price', 'site-reviews' ),
		'placeholder' => '10.00',
		'type' => 'text',
	],
	'settings.schema.highprice' => [
		'default' => '',
		'depends_on' => ['settings.schema.type.default' => 'Product'],
		'description' => __( 'Custom Field name: <code>schema_highprice</code>', 'site-reviews' ),
		'label' => __( 'High Price', 'site-reviews' ),
		'placeholder' => '100.00',
		'type' => 'text',
	],
	'settings.schema.pricecurrency' => [
		'default' => '',
		'depends_on' => ['settings.schema.type.default' => 'Product'],
		'description' => __( 'Custom Field name: <code>schema_pricecurrency</code>', 'site-reviews' ),
		'label' => __( 'Price Currency', 'site-reviews' ),
		'placeholder' => 'USD',
		'type' => 'text',
	],
	'settings.submissions.style' => [
		'default' => 'default',
		'description' => __( 'Site Reviews relies on the CSS of your theme to style the submission form. If your theme does not provide proper CSS rules for form elements and you are using a WordPress plugin/theme or CSS Framework listed here, please try selecting it, otherwise choose "Site Reviews (default)".', 'site-reviews' ),
		'label' => __( 'Form Style', 'site-reviews' ),
		'options' => [
			'bootstrap_4' => 'Bootstrap 4',
			'bootstrap_4_custom' => 'Bootstrap 4 (Custom Forms)',
			'contact_form_7' => 'Contact Form 7 (v5)',
			'divi' => 'Divi (v3)',
			'ninja_forms' => 'Ninja Forms (v3)',
			'default' => __( 'Site Reviews (default)', 'site-reviews' ),
			'minimal' => __( 'Site Reviews (minimal)', 'site-reviews' ),
			'twentyfifteen' => 'Twenty Fifteen',
			'twentyseventeen' => 'Twenty Seventeen',
			'wpforms' => 'WPForms Lite (v1)',
		],
		'type' => 'select',
	],
	'settings.submissions.required' => [
		'default' => ['content', 'email', 'name', 'rating', 'terms', 'title'],
		'description' => __( 'Choose which fields should be required in the submission form.', 'site-reviews' ),
		'label' => __( 'Required Fields', 'site-reviews' ),
		'options' => [
			'rating' => __( 'Rating', 'site-reviews' ),
			'title' => __( 'Title', 'site-reviews' ),
			'content' => __( 'Review', 'site-reviews' ),
			'name' => __( 'Name', 'site-reviews' ),
			'email' => __( 'Email', 'site-reviews' ),
			'terms' => __( 'Terms', 'site-reviews' ),
		],
		'type' => 'checkbox',
	],
	'settings.submissions.recaptcha.integration' => [
		'default' => '',
		'description' => __( 'Invisible reCAPTCHA is a free anti-spam service from Google. To use it, you will need to <a href="https://www.google.com/recaptcha/admin" target="_blank">sign up</a> for an API key pair for your site.', 'site-reviews' ),
		'label' => __( 'Invisible reCAPTCHA', 'site-reviews' ),
		'options' => [
			'' => 'Do not use reCAPTCHA',
			'all' => 'Use reCAPTCHA',
			'guest' => 'Use reCAPTCHA only for guest users',
		],
		'type' => 'select',
	],
	'settings.submissions.recaptcha.key' => [
		'default' => '',
		'depends_on' => ['settings.submissions.recaptcha.integration' => ['all', 'guest']],
		'label' => __( 'Site Key', 'site-reviews' ),
		'type' => 'text',
	],
	'settings.submissions.recaptcha.secret' => [
		'default' => '',
		'depends_on' => ['settings.submissions.recaptcha.integration' => ['all', 'guest']],
		'label' => __( 'Site Secret', 'site-reviews' ),
		'type' => 'text',
	],
	'settings.submissions.recaptcha.position' => [
		'default' => 'bottomleft',
		'depends_on' => ['settings.submissions.recaptcha.integration' => ['all', 'guest']],
		'description' => __( 'This option may not work consistently if another plugin is loading reCAPTCHA on the same page as Site Reviews.', 'site-reviews' ),
		'label' => __( 'Badge Position', 'site-reviews' ),
		'options' => [
			'bottomleft' => 'Bottom Left',
			'bottomright' => 'Bottom Right',
			'inline' => 'Inline',
		],
		'type' => 'select',
	],
	'settings.submissions.akismet' => [
		'default' => 'no',
		'description' => __( 'The <a href="https://akismet.com" target="_blank">Akismet plugin</a> integration provides spam-filtering for your reviews. In order for this setting to have any affect, you will need to first install and activate the Akismet plugin and set up a WordPress.com API key.', 'site-reviews' ),
		'label' => __( 'Enable Akismet Integration', 'site-reviews' ),
		'type' => 'yes_no',
	],
	'settings.submissions.blacklist.entries' => [
		'default' => '',
		'description' => __( 'When a review contains any of these words in its title, content, name, email, or IP address, it will be rejected. One word or IP address per line. It will match inside words, so "press" will match "WordPress".', 'site-reviews' ),
		'label' => __( 'Review Blacklist', 'site-reviews' ),
		'rows' => 10,
		'type' => 'code',
	],
	'settings.submissions.blacklist.action' => [
		'default' => 'unapprove',
		'description' => __( 'Choose the action that should be taken when a review is blacklisted.', 'site-reviews' ),
		'label' => __( 'Blacklist Action', 'site-reviews' ),
		'options' => [
			'unapprove' => __( 'Require approval', 'site-reviews' ),
			'reject' => __( 'Reject submission', 'site-reviews' ),
		],
		'type' => 'select',
	],
];
