<?php

/**
 * breakdance 2.8.1
 * Generated by tests/bin/generate-stubs.php — do not edit, rerun `make stubs`.
 * Source: tests/bin/zips/breakdance.zip
 */

namespace Breakdance {
    trait Singleton
    {
        /** @var self|null */
        private static $instance = null;
        /**
         * @return self
         */
        final public static function getInstance(): self
        {
        }
        // Prevent cloning of the instance
        public function __clone()
        {
        }
        // Prevent deserialization of the instance
        public function __wakeup()
        {
        }
    }
}
namespace Breakdance\Elements {
    class Element
    {
        /**
         * @return string
         */
        public static function defaultTag()
        {
        }
        /**
         * @return string
         * @psalm-suppress InvalidFalsableReturnType
         */
        public static function uiIcon()
        {
        }
        /**
         * @return string[]
         */
        public static function tagOptions()
        {
        }
        /**
         * @return string|false
         */
        public static function tagControlPath()
        {
        }
        /**
         * @return string
         */
        public static function template()
        {
        }
        /**
         * @return string
         * @psalm-suppress InvalidFalsableReturnType
         */
        public static function slug()
        {
        }
        /**
         * @return string|false
         */
        public static function name()
        {
        }
        /**
         * @return string|false
         */
        public static function className()
        {
        }
        /**
         * @return string
         */
        public static function category()
        {
        }
        /**
         * @return mixed|false
         */
        public static function badge()
        {
        }
        /**
         * @return Control[]
         */
        public static function contentControls()
        {
        }
        /**
         * @return Control[]
         */
        public static function designControls()
        {
        }
        /**
         * @return Control[]
         */
        public static function settingsControls()
        {
        }
        /**
         * @return DynamicPropertyPath[]|false|null
         */
        public static function dynamicPropertyPaths()
        {
        }
        /**
         * @return mixed
         */
        public static function defaultProperties()
        {
        }
        /**
         * @return false|string[]
         */
        public static function defaultChildren()
        {
        }
        /**
         * @return ElementAttribute[]|false
         */
        public static function attributes()
        {
        }
        /**
         * @return string
         */
        public static function defaultCSS()
        {
        }
        /**
         * @return string
         */
        public static function cssTemplate()
        {
        }
        /**
         * @return ElementDependenciesAndConditions[]|false
         */
        public static function dependencies()
        {
        }
        /**
         * @return ElementSettings|false
         */
        public static function settings()
        {
        }
        /**
         * @return BuilderActions|false
         */
        public static function actions()
        {
        }
        /**
         * @return array{location:string,cssProperty:string,affectedPropertyPath:string}[]|false
         */
        public static function spacingBars()
        {
        }
        /**
         * @return mixed
         */
        public static function nestingRule()
        {
        }
        /**
         * @return string
         */
        public static function tag()
        {
        }
        /**
         * @param mixed $propertiesData
         * @param mixed $parentPropertiesData
         * @param bool $isBuilder
         * @param int $repeaterItemNodeId
         * @return string
         */
        public static function ssr($propertiesData, $parentPropertiesData = [], $isBuilder = false, $repeaterItemNodeId = null)
        {
        }
        /**
         * @return false|mixed
         */
        public static function addPanelRules()
        {
        }
        public static function requiredPlugins()
        {
        }
        /**
         * @return boolean
         */
        public static function experimental()
        {
        }
        /**
         * @return string[]
         */
        public static function availableIn()
        {
        }
        /**
         * @return int
         */
        public static function order()
        {
        }
        /**
         * @return array{name:string,template:string}[]|false
         */
        public static function additionalClasses()
        {
        }
        /**
         * @return mixed|false
         */
        public static function projectManagement()
        {
        }
        /**
         * @return string[]|false
         */
        public static function propertyPathsToWhitelistInFlatProps()
        {
        }
        /**
         * @return string[]|false
         */
        public static function propertyPathsToSsrElementWhenValueChanges()
        {
        }
    }
}
namespace Breakdance\Elements\PresetSections {
    class PresetSectionsController
    {
        use \Breakdance\Singleton;
        /**
         * @var Preset[]
         */
        public $presets = [];
        /**
         * @param string $slug
         * @param Control $section
         * @param boolean $availableInElementStudio
         * @param array{relativePropertyPathsToWhitelistInFlatProps?: string[], relativeDynamicPropertyPaths?: DynamicPropertyPath[], codeHelp?: string}|null $options
         */
        public function register($slug, $section, $availableInElementStudio = false, $options = null)
        {
        }
        /**
         * @return Preset[]
         */
        public function getAvailableInElementStudio()
        {
        }
    }
}
namespace Breakdance\Lib\Vendor\League\HTMLToMarkdown {
    interface ElementInterface
    {
        public function isBlock(): bool;
        public function isText(): bool;
        public function isWhitespace(): bool;
        public function getTagName(): string;
        public function getValue(): string;
        public function hasParent(): bool;
        public function getParent(): ?\Breakdance\Lib\Vendor\League\HTMLToMarkdown\ElementInterface;
        public function getNextSibling(): ?\Breakdance\Lib\Vendor\League\HTMLToMarkdown\ElementInterface;
        public function getPreviousSibling(): ?\Breakdance\Lib\Vendor\League\HTMLToMarkdown\ElementInterface;
        /**
         * @param string|string[] $tagNames
         */
        public function isDescendantOf($tagNames): bool;
        public function hasChildren(): bool;
        /**
         * @return ElementInterface[]
         */
        public function getChildren(): array;
        public function getNext(): ?\Breakdance\Lib\Vendor\League\HTMLToMarkdown\ElementInterface;
        public function getSiblingPosition(): int;
        public function getChildrenAsString(): string;
        public function setFinalMarkdown(string $markdown): void;
        public function getListItemLevel(): int;
        public function getAttribute(string $name): string;
    }
}
namespace EssentialElements {
    class Formdesignoptions extends \Breakdance\Elements\Element
    {
        static function uiIcon()
        {
        }
        static function tag()
        {
        }
        static function tagOptions()
        {
        }
        static function tagControlPath()
        {
        }
        static function name()
        {
        }
        static function className()
        {
        }
        static function category()
        {
        }
        static function badge()
        {
        }
        static function slug()
        {
        }
        static function template()
        {
        }
        static function defaultCss()
        {
        }
        static function defaultProperties()
        {
        }
        static function defaultChildren()
        {
        }
        static function cssTemplate()
        {
        }
        static function designControls()
        {
        }
        static function contentControls()
        {
        }
        static function settingsControls()
        {
        }
        static function dependencies()
        {
        }
        static function settings()
        {
        }
        static function addPanelRules()
        {
        }
        public static function actions()
        {
        }
        static function nestingRule()
        {
        }
        static function spacingBars()
        {
        }
        static function attributes()
        {
        }
        static function experimental()
        {
        }
        static function availableIn()
        {
        }
        static function order()
        {
        }
        static function dynamicPropertyPaths()
        {
        }
        static function additionalClasses()
        {
        }
        static function projectManagement()
        {
        }
        static function propertyPathsToWhitelistInFlatProps()
        {
        }
        static function propertyPathsToSsrElementWhenValueChanges()
        {
        }
    }
}
namespace Breakdance\AJAX {
    /**
     * @param string $route
     * @param callable $callback
     * @param string $minimum_permissions
     * @param bool $any_url
     * @param RegisterAjaxHandlerOptions $options
     * @param bool $skip_nonce_check
     * @return void
     * @throws \Exception
     *
     * In case of renaming/moving to another namespace don't forget to adjust the readme.md file
     */
    function register_handler($route, callable $callback, $minimum_permissions = 'never', $any_url = false, $options = [], $skip_nonce_check = false)
    {
    }
    /**
     * @return string
     */
    function get_nonce_key_for_ajax_requests()
    {
    }
    /**
     * @return string
     */
    function get_nonce_for_ajax_requests()
    {
    }
}
namespace Breakdance\ElementStudio {
    /**
     * @param  string  $directoryPath - e.g: $directoryPath = getDirectoryPathRelativeToPluginFolder(__DIR__) . '/elements'
     * @param  string  $namespace
     * @param 'element'|'macro'|'preset' $type
     * @param string $label
     * @param boolean $onlyForAdvancedUsers
     * @param boolean $excludeFromElementStudio
     *
     * @return void
     *
     */
    function registerSaveLocation($directoryPath, $namespace, $type, $label, $onlyForAdvancedUsers, $excludeFromElementStudio = false)
    {
    }
}
namespace Breakdance\Elements {
    /**
     * @param string $slug
     * @param string $label
     * @return void
     */
    function registerCategory($slug, $label)
    {
    }
}
namespace Breakdance\Elements {
    // used by element studio... all the others should be ditched
    /**
     * @param string $slug
     * @param string $label
     * @param array $children
     * @param mixed $options
     * @param boolean $enable_media_queries
     * @param boolean $enable_hover
     * @param array $keywords
     * @param array{accepts: string, proOnly?: boolean}|null $dynamic
     * @return Control
     */
    function c($slug, $label, $children, $options, $enable_media_queries, $enable_hover, $keywords = [], $dynamic = null)
    {
    }
}
namespace Breakdance\Elements\PresetSections {
    /**
     *
     * @param string $presetSlug
     * @param false|string $label
     * @param false|string $sectionSlug
     * @param false|mixed $options
     * @return Control
     */
    function getPresetSection($presetSlug, $label = false, $sectionSlug = false, $options = false)
    {
    }
}
namespace Breakdance\Permissions {
    /**
     * @param string $minimumPermission
     * @param int|\WP_User $userId
     * @return bool
     * @throws \Exception
     */
    function hasMinimumPermission($minimumPermission, $userId = 0)
    {
    }
}
namespace {
    const __BREAKDANCE_VERSION = '2.8.1';
}
