<?php

/**
 * buddyboss 3.4.0
 * Generated by tests/bin/generate-stubs.php — do not edit, rerun `make stubs:update`.
 * Source: https://codeload.github.com/buddyboss/buddyboss-platform/zip/refs/tags/3.4.0
 */

namespace {
    /**
     * Get the ID of the currently displayed user.
     *
     * @since BuddyPress 1.0.0
     *
     * @return int $id ID of the currently displayed user.
     */
    function bp_displayed_user_id()
    {
    }
}
