<?php

/**
 * flatsome 3.20.8
 * Generated by tests/bin/generate-stubs.php — do not edit, rerun `make stubs`.
 * Source: tests/bin/zips/flatsome.zip
 */

namespace {
    /**
     * Register a shortcode element.
     *
     * @param string $type The shortcode tag name
     * @param array  $options
     */
    function add_ux_builder_shortcode($type, $options)
    {
    }
}
