<?php

/**
 * fusion-builder 3.15.5
 * Generated by tests/bin/generate-stubs.php — do not edit, rerun `make stubs`.
 * Source: tests/bin/zips/fusion-builder.zip
 */

namespace {
    \define('FUSION_BUILDER_VERSION', '3.15.5');
}
namespace {
    /**
     * Builder Elements Class.
     *
     * @since 1.1.0
     */
    abstract class Fusion_Element
    {
        /**
         * FB options class object.
         *
         * @static
         * @access protected
         * @since 1.1.0
         * @var Fusion_Builder_Options|null
         */
        protected static $fb_options;
        /**
         * First add on or not.
         *
         * @static
         * @access protected
         * @since 1.1.0
         * @var boolean
         */
        protected static $first_addon = \true;
        /**
         * Dynamic CSS class object.
         *
         * @static
         * @access protected
         * @since 1.1.0
         * @var bool
         */
        protected static $dynamic_css_helpers;
        /**
         * Options array.
         * THis holds ALL OPTIONS from ALL ELEMENTS.
         *
         * @static
         * @access protected
         * @since 1.1.0
         * @var array
         */
        protected static $global_options = [];
        /**
         * Element ID.
         *
         * @access protected
         * @since 2.0
         * @var string|int
         */
        protected $element_id;
        /**
         * An array of the shortcode defaults.
         *
         * @access protected
         * @since 3.0
         * @var array
         */
        protected $defaults;
        /**
         * Whether it has rendered already or not.
         *
         * @access protected
         * @since 3.0
         * @var bool
         */
        protected $has_rendered = \false;
        /**
         * The element arguments.
         *
         * @var array
         */
        protected $args = [];
        /**
         * Dynamic CSS for creating style CSS.
         *
         * @var array
         */
        public $dynamic_css = [];
        /**
         * The class constructor
         *
         * @access private
         */
        public function __construct()
        {
        }
        /**
         * Add CSS to dynamic CSS.
         *
         * @access protected
         * @since 2.0
         */
        public function load_css()
        {
        }
        /**
         * Add CSS to dynamic CSS.
         *
         * @access protected
         * @since 3.0
         */
        public function add_css_files()
        {
        }
        /**
         * Adds settings to element options panel.
         *
         * @access protected
         * @since 1.1
         */
        protected function add_options()
        {
        }
        /**
         * Checks location of child class.
         *
         * @access protected
         * @since 1.1
         */
        protected function get_dir()
        {
        }
        /**
         * Adds scripts to the dynamic JS.
         *
         * @access protected
         * @since 1.1.0
         */
        protected function add_scripts()
        {
        }
        /**
         * Adds dynamic styling to dynamic CSS.
         *
         * @access protected
         * @since 1.1
         */
        protected function add_styling()
        {
        }
        /**
         * Fires on render.
         *
         * @access protected
         * @since 3.2
         */
        protected function on_render()
        {
        }
        /**
         * Fires on first render only.
         *
         * @access protected
         * @since 3.2
         */
        protected function on_first_render()
        {
        }
        /**
         * Ensure scripts are loaded for live editor.
         *
         * @access public
         * @since 3.2
         */
        public function live_editor_scripts()
        {
        }
        /**
         * Sets the ID for the element.
         *
         * @access protected
         * @param int $count Count of element or ID.
         * @since 2.0
         */
        protected function set_element_id($count)
        {
        }
        /**
         * Gets the ID for the element.
         *
         * @access protected
         * @since 2.0
         * @return string
         */
        protected function get_element_id()
        {
        }
        /**
         * Returns the $global_options property.
         *
         * @static
         * @access public
         * @since 1.1.0
         * @return array
         */
        public static function get_all_options()
        {
        }
        /**
         * Check if a param is default.
         *
         * @access public
         * @since 3.0
         * @param string $param Param name.
         * @return bool
         */
        public function is_default($param)
        {
        }
        /**
         * Add CSS property to overall array.
         *
         * @access protected
         * @since 3.0
         * @param mixed  $selectors CSS selector, array or string.
         * @param string $property CSS property.
         * @param string $value CSS value.
         * @param bool   $important Whether it is important or not.
         * @return void
         */
        protected function add_css_property($selectors = [], $property = '', $value = '', $important = \false)
        {
        }
        /**
         * Get a string with each of the option as a CSS variable, if the option is not default.
         *
         * @since 3.9
         * @param array $options  The array with the options ids.
         * @return string
         */
        protected function get_css_vars_for_options($options)
        {
        }
        /**
         * Get a string with custom CSS variables, created from array key => value pairs.
         *
         * @since 3.9
         * @param array   $options The array with the custom css vars. The key
         *   represents the option name, while the value represents the custom value.
         * @param boolean $prefix Whether to alter the variable name or not.
         * @return string
         */
        protected function get_custom_css_vars($options, $prefix = \true)
        {
        }
        /**
         * Get font styling vars, created from get_font_styling helper.
         *
         * @since 3.9
         * @param string $key Typography options key.
         * @return string
         */
        protected function get_font_styling_vars($key)
        {
        }
        /**
         * Get declaration for typography vars with the given values.
         *
         * @since 3.9
         * @param string $title_tag An HTML tag, Ex: 'h2', 'h3', 'div'.. etc.
         * @param array  $name_value_map The key is a css property, the array value is the CSS value.
         * @return string
         */
        protected function get_heading_font_vars($title_tag, $name_value_map)
        {
        }
        /**
         * Get aspect ratio vars.
         *
         * @since 3.9
         * @return string
         */
        protected function get_aspect_ratio_vars()
        {
        }
        /**
         * Get from ACF repeater for parent and child elements.
         *
         * @since 3.9
         * @param array  $dynamic_data The dynamic data.
         * @param array  $args The arguments.
         * @param string $content The content.
         * @param bool   $rendered Whether or not is rendered.
         * @return string
         */
        public static function get_acf_repeater($dynamic_data, $args, $content, $rendered = \true)
        {
        }
        /**
         * Add CSS property to overall array.
         *
         * @access protected
         * @since 3.0
         * @return string
         */
        protected function parse_css()
        {
        }
        /**
         * Filter the post ID for use as dynamic data source.
         *
         * @access public
         * @since 1.0
         * @return array
         */
        public function post_dynamic_data()
        {
        }
    }
    /**
     * The main FusionBuilder class.
     *
     * @package fusion-builder
     * @since 2.0
     */
    /**
     * Main FusionBuilder Class.
     *
     * @since 1.0
     */
    class FusionBuilder
    {
        /**
         * The one, true instance of this object.
         *
         * @static
         * @access private
         * @since 1.0
         * @var FusionBuilder|null
         */
        private static $instance;
        /**
         * An array of allowed post types.
         *
         * @static
         * @access private
         * @since 1.0
         * @var array
         */
        private static $allowed_post_types = [];
        /**
         * An array of the element option descriptions.
         *
         * @static
         * @access public
         * @since 2.0
         * @var array
         */
        public static $element_descriptions_map = [];
        /**
         * An array of the element option dependencies.
         *
         * @static
         * @access public
         * @since 2.0
         * @var array
         */
        public static $element_dependency_map = [];
        /**
         * An array of the base element CSS files.
         *
         * @access public
         * @since 3.0
         * @var array
         */
        public $element_css_files = [];
        /**
         * Fusion_Product_Registration
         *
         * @access public
         * @var object Fusion_Product_Registration.
         */
        public $registration;
        /**
         * Fusion_Images.
         *
         * @access public
         * @var object
         */
        public $images;
        /**
         * An array of body classes to be added.
         *
         * @access private
         * @since 1.1
         * @var array
         */
        private $body_classes = [];
        /**
         * Determine if we're currently upgrading/migration options.
         *
         * @static
         * @access public
         * @var bool
         */
        public static $is_updating = \false;
        /**
         * Determine if we're currently upgrading plugin.
         *
         * @static
         * @access public
         * @var bool
         */
        public static $is_upgrading = \false;
        /**
         * The Fusion_Builder_Options_Panel object.
         *
         * @access private
         * @since 1.1.0
         * @var object
         */
        private $fusion_builder_options_panel;
        /**
         * The Fusion_Builder_Dynamic_CSS object.
         *
         * @access private
         * @since 1.1.3
         * @var object
         */
        private $fusion_builder_dynamic_css;
        /**
         * URL to the js files.
         *
         * @static
         * @access public
         * @since 1.1.3
         * @var string
         */
        public static $js_folder_url;
        /**
         * Path to the js files.
         *
         * @static
         * @access public
         * @since 1.1.3
         * @var string
         */
        public static $js_folder_path;
        /**
         * Shortcode array for live builder.
         *
         * @access public
         * @var array $shortcode_array.
         */
        public $shortcode_array;
        /**
         * Parent id scope for shortcode render.
         *
         * @access public
         * @var mixed $shortcode_parent.
         */
        public $shortcode_parent;
        /**
         * Extra fonts for page to load.
         *
         * @access public
         * @since 2.2
         * @var mixed
         */
        public $extra_fonts = \null;
        /**
         * Custom conditions.
         *
         * @access private
         * @since 3.9
         * @var mixed
         */
        private $custom_conditions = \null;
        /**
         * Custom form actions.
         *
         * @access private
         * @since 3.9
         * @var mixed
         */
        private $custom_form_actions = \null;
        /**
         * An array of all the menus found for current page load.
         *
         * @static
         * @access public
         * @since 3.9
         * @var array
         */
        public $menus = [];
        /**
         * Post card data.
         *
         * @access public
         * @since 3.3
         * @var array
         */
        public $post_card_data = ['is_rendering' => \false, 'is_post_card_archives' => \false, 'columns' => 1, 'column_spacing' => 0];
        /**
         * If we are editing post card in Live Editor.
         *
         * @access public
         * @since 3.3
         * @var boolean
         */
        public $editing_post_card = \false;
        /**
         * Mega menu data.
         *
         * @access public
         * @since 3.3
         * @var array
         */
        public $mega_menu_data = ['is_rendering' => \false];
        /**
         * If we are editing mega menu in Live Editor.
         *
         * @access public
         * @since 3.3
         * @var boolean
         */
        public $editing_mega_menu = \false;
        /**
         * Reference to Fusion_Builder_Gutenberg class.
         *
         * @var Fusion_Builder_Gutenberg|null
         */
        public $fusion_builder_gutenberg;
        /**
         * Reference to Fusion_Builder_Gutenberg class.
         *
         * @var Fusion_Dynamic_Data|null
         */
        public $dynamic_data;
        /**
         * Creates or returns an instance of this class.
         *
         * @static
         * @access public
         * @since 1.0
         */
        public static function get_instance()
        {
        }
        /**
         * Initializes the plugin by setting localization, hooks, filters,
         * and administrative functions.
         *
         * @access private
         * @since 1.0
         */
        private function __construct()
        {
        }
        /**
         * Initializes the plugin by setting localization, hooks, filters,
         * and administrative functions.
         *
         * @access public
         * @since 1.0
         */
        public function init()
        {
        }
        /**
         * Sanitizes content for allowed HTML tags for post content on render.
         *
         * @access public
         * @since 7.11.10
         * @param string $content Post content to filter, expected to be escaped with slashes.
         * @return string Filtered post content with allowed HTML tags and attributes intact.
         */
        public function filter_post_content_on_render($content)
        {
        }
        /**
         * Sanitizes content for allowed HTML tags for post content.
         *
         * @access public
         * @since 7.11.10
         * @param array $content Elementor element array, decoded from JSON.
         * @return array Filtered Elementor element array.
         */
        public function parse_elementor_content($content)
        {
        }
        /**
         * Callback for filtering Elementor content.
         *
         * @access public
         * @since 7.11.10
         * @param array $post_content Matched Elementor content from the "editor" indices.
         * @return strin Filtered Elementor content.
         */
        public function filter_elementor_content($post_content)
        {
        }
        /**
         * Sanitizes content to be run through KSES.
         * This function expects slashed data.
         *
         * @access public
         * @since 7.11.10
         * @param string         $content           Content to filter through KSES.
         * @param array[]|string $allowed_html      An array of allowed HTML elements and attributes,
         *                                          or a context name such as 'post'. See wp_kses_allowed_html()
         *                                          for the list of accepted context names.
         * @param string[]       $allowed_protocols Array of allowed URL protocols.
         * @return string Filtered post content with allowed HTML tags and attributes intact.
         */
        public function filter_post_content_pre_kses($content, $allowed_html, $allowed_protocols)
        {
        }
        /**
         * Sanitizes content for allowed HTML tags for post content.
         *
         * @access public
         * @since 7.11.7
         * @param string $post_content Post content to filter, expected to be escaped with slashes.
         * @param bool   $handle_slashes Decides if we need to strip slashes or not.
         * @param bool   $force_check Decides if we need to run the filtering in any case.
         * @return string Filtered post content with allowed HTML tags and attributes intact.
         */
        public function filter_post_content($post_content, $handle_slashes = \true, $force_check = \false)
        {
        }
        /**
         * Sanitizes URLs and link attributes passed from post content that start with parameter name.
         *
         * @access public
         * @since 7.11.7
         * @param string $link_param The URL or link param to be sanitized starting with link=", link_url=", url=",  href=", full_image="', video_url=" or link_attributes=".
         * @return string Sanitized URL or link param.
         */
        public function process_urls_and_links($link_param)
        {
        }
        /**
         * Sanitizes code block element in post content.
         *
         * @access public
         * @since 7.11.7
         * @param string $code_block The code block including shortcode tags.
         * @return string Sanitized code block.
         */
        public function process_code_block($code_block)
        {
        }
        /**
         * Sanitizes Form Notice element in post content.
         *
         * @access public
         * @since 3.15.0
         * @param string $param The shortcode.
         * @return string Sanitized param.
         */
        public function process_form_notice($matches)
        {
        }
        /**
         * Do the action fusion_builder_wp_loaded.
         *
         * @since 3.9
         * @return void
         */
        public function do_fusion_builder_wp_loaded()
        {
        }
        /**
         * Getter for $is_upgrading static var.
         *
         * @access public
         * @since 3.1
         * @return bool.
         */
        public static function is_upgrading()
        {
        }
        /**
         * Returns whether or not page has extra google fonts.
         *
         * @access public
         * @since 2.0
         * @param mixed $has_extra Has extra google fonts.
         */
        public function has_extra_google_fonts($has_extra)
        {
        }
        /**
         * Find and merge fonts for nested forms and post cards.
         *
         * @access public
         * @since 3.5
         * @param array  $extra_fonts Fonts already from content.
         * @param string $content Content we are searching for content.
         */
        public function get_nested_fonts($extra_fonts = [], $content = '')
        {
        }
        /**
         * Safely resolve a "_fusion_google_fonts" meta value to its fonts array.
         *
         * Legitimate fonts data is stored as an array, which get_post_meta() already
         * returns unserialized. A second maybe_unserialize() on a string value would
         * instantiate arbitrary PHP objects.
         *
         * @access private
         * @since 3.15.5
         * @param mixed $value Raw meta value (array, serialized string, or scalar).
         * @return mixed The fonts array, or the original value when it is not a serialized string.
         */
        private function awb_safe_unserialize_fonts($value)
        {
        }
        /**
         * Get extra fonts.
         *
         * @access public
         * @since 2.2
         * @return mixed.
         */
        public function get_extra_google_fonts()
        {
        }
        /**
         * Sets inline google fonts to be enqueued.
         *
         * @access public
         * @since 2.0
         * @param mixed $fonts Fonts.
         */
        public function set_extra_google_fonts($fonts)
        {
        }
        /**
         * Helper function for PHP 5.2 compatibility in the next_page method.
         *
         * @access private
         * @since 1.1.0
         * @param mixed $p Posts.
         */
        private function next_page_helper($p)
        {
        }
        /**
         * Replace fusion_builder_next_page shortcode with <!--nextpage-->
         *
         * @access public
         * @since 1.1
         * @param array $posts The array of posts.
         */
        public function next_page($posts)
        {
        }
        /**
         * Set WP editor settings.
         *
         * @access public
         * @since 1.0
         */
        public function enqueue_wp_editor_scripts()
        {
        }
        /**
         * Processes that must run when the plugin is activated.
         *
         * @static
         * @access public
         * @since 1.0
         */
        public static function activation()
        {
        }
        /**
         * Activate Convertplug element on plugin activation.
         *
         * @static
         * @access public
         * @since 1.7
         */
        public function activate_convertplug_element()
        {
        }
        /**
         * Processes that must run when the plugin is deactivated.
         *
         * @static
         * @access public
         * @since 1.1
         */
        public static function deactivation()
        {
        }
        /**
         * Add TinyMCE rich editor button.
         *
         * @access public
         * @since 1.0
         * @param array $buttons The array of available buttons.
         * @return array
         */
        public function register_rich_buttons($buttons)
        {
        }
        /**
         * Add Avada Builder menu icon.
         *
         * @access public
         * @since 1.0
         */
        public function admin_styles()
        {
        }
        /**
         * Define TinyMCE rich editor js plugin.
         *
         * @access public
         * @since 1.0
         * @param array $plugin_array The plugins array.
         * @return array.
         */
        public function add_rich_plugins($plugin_array)
        {
        }
        /**
         * Set global variables.
         *
         * @access public
         * @since 1.0
         */
        public function init_global_vars()
        {
        }
        /**
         * Find and include all shortcodes within shortcodes folder.
         *
         * @access public
         * @since 1.0
         * @return void
         */
        public function init_shortcodes()
        {
        }
        /**
         * Add helper meta box on allowed post types.
         *
         * @access public
         * @since 1.0
         * @param mixed $post The post (not used in this context).
         */
        public function single_settings_meta_box($post)
        {
        }
        /**
         * Add Fusion library message meta box.
         *
         * @access public
         * @since 1.0
         * @param mixed $post The post (not used in this context).
         */
        public function library_single_message_box($post)
        {
        }
        /**
         * Add Helper MetaBox.
         *
         * @access public
         * @since 1.0
         */
        public function add_builder_helper_meta_box()
        {
        }
        /**
         * Save Helper MetaBox Settings.
         *
         * @access public
         * @since 1.0
         * @param int|string $post_id The post ID.
         * @param object     $post    The post.
         * @return int|void
         */
        public function metabox_settings_save_details($post_id, $post)
        {
        }
        /**
         * Fix shortcode content on front end by getting rid of random p tags.
         *
         * @access public
         * @since 1.0
         * @param string $content The content.
         * return string          The content, modified.
         */
        public function fix_builder_shortcodes($content)
        {
        }
        /**
         * Count the containers of a page.
         *
         * @access public
         * @since 1.3
         * @param string $content The content.
         * @return string $content
         */
        public function fusion_calculate_containers($content)
        {
        }
        /**
         * Fixes line break issue for shortcodes in widgets.
         *
         * @access public
         * @since  1.2
         * @param  string $widget_instance The widget Instance.
         * @return $instance
         */
        public function fusion_disable_wpautop_in_widgets($widget_instance)
        {
        }
        /**
         * Fixes image src issue for URLs with dashes.
         *
         * @access public
         * @since  1.4
         * @param  Array $shortcodes    Array of shortcodes to exempt.
         * @return $shortcodes
         */
        public function exempt_from_wptexturize($shortcodes)
        {
        }
        /**
         * Helper function that substracts values.
         * Added for compatibility with older PHP versions.
         *
         * @access public
         * @since 1.0.3
         * @param array $a 1st value.
         * @param array $b 2nd value.
         * @return int
         */
        public function column_opening_positions_index_substract($a, $b)
        {
        }
        /**
         * Add shared element styles to the array.
         *
         * @access private
         * @since 3.0
         * @return void
         */
        public function add_shared_element_styles()
        {
        }
        /**
         * Add shared element styles to the array.
         *
         * @access private
         * @since 3.0
         * @param string $file Path to file.
         * @return void
         */
        public function add_element_css($file)
        {
        }
        /**
         * Add shortcode styles in dynamic-css.
         *
         * @access public
         * @since 1.1.5
         * @param string $original_styles The compiled styles.
         * @return string The compiled styles with the new ones appended.
         */
        public function shortcode_styles_dynamic_css($original_styles)
        {
        }
        /**
         * Shortcode Scripts & Styles.
         * Registers the FB library scripts used as dependency.
         *
         * @access public
         * @since 1.1
         * @return void
         */
        public function register_scripts()
        {
        }
        /**
         * Admin Scripts.
         * Enqueues all necessary scripts in the WP Admin to run Avada Builder.
         *
         * @access public
         * @since 1.0
         * @return void
         */
        public function admin_scripts()
        {
        }
        /**
         * Include required files.
         *
         * @access private
         * @since 1.0
         * @return void
         */
        private function includes()
        {
        }
        /**
         * Avada Builder wrapper.
         *
         * @access public
         * @since 1.0
         * @param object $post The post.
         */
        public function before_main_editor($post)
        {
        }
        /**
         * Avada Builder wrapper.
         *
         * @package Avada Builder
         * @author ThemeFusion
         * @param object $post The post.
         */
        public function after_main_editor($post)
        {
        }
        /**
         * Default post types.
         *
         * @package Avada Builder
         * @author ThemeFusion
         * @since 1.0
         */
        public static function default_post_types()
        {
        }
        /**
         * Builder is displayed on the following post types.
         *
         * @package Avada Builder
         * @author ThemeFusion
         */
        public static function allowed_post_types()
        {
        }
        /**
         * Add Page Builder MetaBox.
         *
         * @since 1.0
         * @param  string $post_type  Post type slug.
         * @return void
         */
        public function add_builder_meta_box($post_type)
        {
        }
        /**
         * Resets the meta box priority for Yoast SEO.
         * Devs can override by using fusion_builder_yoast_meta_box_priority filter.
         *
         * @since 1.0.0
         * @access public
         * @return string The meta box priority.
         */
        public function set_yoast_meta_box_priority()
        {
        }
        /**
         * Function to apply attributes to HTML tags.
         * Devs can override attributes in a child theme by using the correct slug.
         *
         * @since 1.0.0
         * @access public
         * @param  string $slug    Slug to refer to the HTML tag.
         * @param  array  $attributes Attributes for HTML tag.
         * @return string The string of all attributes.
         */
        public static function attributes($slug, $attributes = [])
        {
        }
        /**
         * Function to get the default shortcode param values applied.
         *
         * @static
         * @access public
         * @since 1.0
         * @param  array  $defaults  Array of defaults.
         * @param  array  $args      Array with user set param values.
         * @param  string $shortcode Shortcode name.
         * @return array
         */
        public static function set_shortcode_defaults($defaults, $args, $shortcode = \false)
        {
        }
        /**
         * Returns an array with the rgb values.
         *
         * @static
         * @access public
         * @since 1.0
         * @param string $hex The HEX color.
         * @return array
         */
        public static function hex2rgb($hex)
        {
        }
        /**
         * Function to return animation classes for shortcodes mainly.
         *
         * @static
         * @access public
         * @since 1.0
         * @param  array $args Animation type, direction and speed.
         * @return array       Array with data attributes.
         */
        public static function animations($args = [])
        {
        }
        /**
         * Strips the unit from a given value.
         *
         * @static
         * @access public
         * @since 1.0
         * @param  string $value The value with or without unit.
         * @param  string $unit_to_strip The unit to be stripped.
         * @return string   the value without a unit.
         */
        public static function strip_unit($value, $unit_to_strip = 'px')
        {
        }
        /**
         * Get the regular expression to parse a single shortcode.
         *
         * @static
         * @access public
         * @since 1.0
         * @param string $tagname Not used in the context of this function.
         * @return string
         */
        public static function get_shortcode_regex($tagname)
        {
        }
        /**
         * Validate shortcode attribute value.
         *
         * @static
         * @access public
         * @since 1.0
         * @param string $value         The value.
         * @param string $accepted_unit The accepted unit.
         * @param string $bc_support    Return value even if invalid.
         * @return value
         */
        public static function validate_shortcode_attr_value($value, $accepted_unit, $bc_support = \true)
        {
        }
        /**
         * Adds the options in the Fusion_Settings class.
         *
         * @access public
         * @since 1.1.0
         */
        public function add_options_to_fusion_settings()
        {
        }
        /**
         * Gets the value of a page option.
         *
         * @static
         * @access public
         * @param  string  $theme_option Gheme option ID.
         * @param  string  $page_option  Page option ID.
         * @param  integer $post_id      Post/Page ID.
         * @since  1.0.1
         * @return string                Gheme option or page option value.
         */
        public static function get_page_option($theme_option, $page_option, $post_id)
        {
        }
        /**
         * Checks if we're in the migration page.
         * It does that by checking _GET, and then sets the $is_updating property.
         *
         * @access public
         * @since 1.1.0
         */
        public function set_is_updating()
        {
        }
        /**
         * Checks if we're editing Fusion Library element.
         *
         * @access public
         * @since 1.5.2
         * @param array $classes An array of body classes.
         * @return string
         */
        public function admin_body_class($classes)
        {
        }
        /**
         * Adds extra classes for the <body> element, using the 'body_class' filter.
         * Documentation: https://codex.wordpress.org/Plugin_API/Filter_Reference/body_class
         *
         * @since 1.1
         * @param  array $classes CSS classes.
         * @return array The merged and extended body classes.
         */
        public function body_class_filter($classes)
        {
        }
        /**
         * Calculate any extra classes for the <body> element.
         *
         * @return array The needed body classes.
         */
        public function set_body_classes()
        {
        }
        /**
         * Gets the fusion_builder_options_panel private property.
         *
         * @access public
         * @since 1.1.0
         * @return object
         */
        public function get_fusion_builder_options_panel()
        {
        }
        /**
         * Compares db and plugin versions and does stuff if needed.
         *
         * @access private
         * @since 1.1.2
         */
        private function versions_compare()
        {
        }
        /**
         * Compares db and plugin versions and does stuff if needed.
         *
         * @since 1.2.1
         * @access private
         * @param array $links The array of action links.
         * @return Array The $links array plus the added settings link.
         */
        public function add_action_settings_link($links)
        {
        }
        /**
         * Return post types to exclude from events calendar.
         *
         * @since 1.3.0
         * @access public
         * @param array $all_post_types All allowed post types in events calendar.
         * @return array
         */
        public function fusion_builder_exclude_post_type($all_post_types)
        {
        }
        /**
         * Adds media-query styles.
         *
         * @access public
         * @since 6.0.0
         */
        public function add_media_query_styles()
        {
        }
        /**
         * Add element media query styles.
         *
         * @access public
         * @since 2.0
         * @return void
         */
        public function add_element_media_query_styles()
        {
        }
        /**
         * Setup the element option decsription map.
         *
         * @static
         * @access public
         * @since 2.0
         * @return void
         */
        public static function set_element_description_map()
        {
        }
        /**
         * Setup the element option dependency map.
         *
         * @static
         * @access public
         * @since 2.0
         * @return void
         */
        public static function set_element_dependency_map()
        {
        }
        /**
         * Set scope for shortcode IDs.
         *
         * @access public
         * @since 2.0
         * @param int $parent_id Id of parent element.
         * @return void
         */
        public function set_global_shortcode_parent($parent_id)
        {
        }
        /**
         * Get scope for shortcode IDs.
         *
         * @access public
         * @since 2.0
         * @return mixed
         */
        public function get_global_shortcode_parent()
        {
        }
        /**
         * Filters content to add WC checkout form.
         *
         * @access public
         * @since  3.3
         * @param  String $content The page content.
         * @return $content
         */
        public function checkout_elements_wrapper($content)
        {
        }
        /**
         * Ajax get builder rendered content used for SEO plugins -> Rankmath or yoast.
         *
         * @access public
         * @since  3.9
         */
        public function get_builder_rendered_content()
        {
        }
        /**
         * Add rendered content in first load for SEO plugins -> Rankmath or yoast.
         *
         * @access public
         * @since  3.9
         */
        public function add_rendered_content_to_footer()
        {
        }
        /**
         * Registers Rendered content endpoint.
         *
         * @access public
         * @since 3.9
         */
        public function register_rendered_content_endpoint()
        {
        }
        /**
         * Rendered Content endpoint.
         *
         * @access public
         * @param Object $data The enpoint data.
         * @since 3.8
         */
        public function rendered_content_endpoint($data)
        {
        }
        /**
         * Get custom form action data.
         *
         * @access public
         * @since 3.8
         */
        public function get_custom_form_actions()
        {
        }
        /**
         * Does our render logic check pre do_shortcode().
         *
         * Returning a non-false value from filter will short-circuit the
         * shortcode generation process, returning that value instead.
         *
         * @access public
         * @since 3.14.0
         *
         * @param false|string $output Short-circuit return value. Either false or the value to replace the shortcode with.
         * @param string       $tag    Shortcode name.
         * @param array        $attr   Shortcode attributes array, can be empty if the original arguments string cannot be parsed.
         * @param array        $m      Regular expression match array.
         * @return bool|string Either bool false or empty string.
         */
        public function add_render_logic_check_pre_do_shortcode($output, $tag, $atts, $m)
        {
        }
    }
}
namespace {
    /**
     * Instantiates the FusionBuilder class.
     * Make sure the class is properly set-up.
     * The FusionBuilder class is a singleton
     * so we can directly access the one true FusionBuilder object using this function.
     *
     * @return object FusionBuilder
     */
    function FusionBuilder()
    {
    }
    /**
     * Taxonomies.
     *
     * @since 1.0
     * @param string $taxonomy           The taxonomy.
     * @param bool   $empty_choice       If this is an empty choice or not.
     * @param string $empty_choice_label The label for empty choices.
     * @param int    $max_cat           The maximum number of tags to return.
     * @return array
     */
    function fusion_builder_shortcodes_categories($taxonomy, $empty_choice = \false, $empty_choice_label = \false, $max_cat = 0)
    {
    }
    /**
     * Auto activate Avada Builder element. To be used by addon plugins.
     *
     * @since 1.0.4
     * @param string $shortcode Shortcode tag.
     */
    function fusion_builder_auto_activate_element($shortcode)
    {
    }
    /**
     * Merges the front-end editor data into map.
     *
     * @since 2.0
     * @param  string $class_name class for shortcode.
     * @param  array  $map     Array map for shortcode.
     * @param  string $context Parent or child level.
     * @return array
     */
    function fusion_builder_frontend_data($class_name, $map, $context = '')
    {
    }
    /**
     * Checks if on an editor page.
     *
     * @since 2.0
     * @return boolean Whether or not it is a fusion editor page.
     */
    function is_fusion_editor()
    {
    }
    /**
     * Add an element to $fusion_builder_elements array.
     *
     * @param array $module The element we're loading.
     */
    function fusion_builder_map($module)
    {
    }
}
