<?php

/**
 * ultimate-member 2.12.1
 * Generated by tests/bin/generate-stubs.php — do not edit, rerun `make stubs:update`.
 * Source: https://downloads.wordpress.org/plugin/ultimate-member.latest-stable.zip
 */

namespace {
    /**
     * Class UM_Functions
     */
    class UM_Functions
    {
        /**
         * Store URL
         *
         * @var string
         */
        public static $store_url = 'https://ultimatemember.com/?edd-request=get-info';
        /**
         * WP remote Post timeout
         * @var int
         */
        public static $request_timeout = 60;
        /**
         * Check if AJAX now
         *
         * @return bool
         */
        function is_ajax()
        {
        }
        /**
         * Check frontend nonce
         *
         * @param bool $action
         */
        function check_ajax_nonce($action = \false)
        {
        }
        /**
         * Check if the user rate limit has been reached based on the provided context
         *
         * @param string   $context      The context for which the rate limit check is being performed
         * @param int|null $requests_num Number requests per minute. Default 10.
         *
         * @return bool True if the rate limit has been reached, false otherwise
         */
        public function is_rate_limited($context, $requests_num = 10)
        {
        }
        /**
         * What type of request is this?
         *
         * @param string $type String containing name of request type (ajax, frontend, cron or admin)
         *
         * @return bool
         */
        public function is_request($type)
        {
        }
        /**
         * Help Tip displaying
         *
         * Function for render/displaying UltimateMember help tip
         *
         * @since  2.0.0
         *
         * @param string $tip Help tip text
         * @param bool $allow_html Allow sanitized HTML if true or escape
         * @param bool $echo Return HTML or echo
         * @return string
         */
        function tooltip($tip, $allow_html = \false, $echo = \true)
        {
        }
        /**
         * @return mixed|void
         */
        function excluded_taxonomies()
        {
        }
        /**
         * Output templates
         *
         * @access public
         * @param string $template_name
         * @param string $basename (default: '')
         * @param array $t_args (default: array())
         * @param bool $echo
         *
         * @return string|void
         */
        public function get_template($template_name, $basename = '', $t_args = array(), $echo = \false)
        {
        }
        /**
         * Locate a template and return the path for inclusion.
         *
         * @access public
         * @param string $template_name
         * @param string $path (default: '')
         * @return string
         */
        function locate_template($template_name, $path = '')
        {
        }
        /**
         * @deprecated 2.8.0
         *
         * @return array
         */
        public function cpt_list()
        {
        }
        /**
         * @param array $array
         * @param string $key
         * @param array $insert_array
         *
         * @return array
         */
        function array_insert_before($array, $key, $insert_array)
        {
        }
        /**
         * @since 2.1.0
         *
         * @param $var
         * @return array|string
         */
        function clean_array($var)
        {
        }
        /**
         * Replace the first match in the string, alternative for the `str_replace()` function
         *
         * @param string $search
         * @param string $replace
         * @param string $subject
         *
         * @return string
         */
        function str_replace_first($search, $replace, $subject)
        {
        }
        /**
         * @param string $context
         *
         * @return array
         */
        public function get_allowed_html($context = '')
        {
        }
    }
    /**
     * Main UM Class
     *
     * @class UM
     * @version 2.0
     *
     * @method UM_bbPress_API bbPress_API()
     * @method UM_Followers_API Followers_API()
     * @method UM_Friends_API Friends_API()
     * @method UM_Mailchimp Mailchimp()
     * @method UM_Messaging_API Messaging_API()
     * @method UM_myCRED myCRED()
     * @method UM_Notices Notices()
     * @method UM_Notifications_API Notifications_API()
     * @method UM_Online Online()
     * @method UM_Profile_Completeness_API Profile_Completeness_API()
     * @method UM_reCAPTCHA reCAPTCHA()
     * @method UM_Reviews Reviews()
     * @method UM_Activity_API Activity_API()
     * @method UM_Social_Login_API Social_Login_API()
     * @method UM_User_Tags User_Tags()
     * @method UM_Verified_Users_API Verified_Users_API()
     * @method UM_WooCommerce_API WooCommerce_API()
     * @method UM_Terms_Conditions Terms_Conditions()
     * @method UM_Private_Content Private_Content()
     * @method UM_User_Locations User_Locations()
     * @method UM_User_Photos User_Photos()
     * @method UM_Groups Groups()
     * @method UM_Frontend_Posting Frontend_Posting()
     * @method UM_Notes Notes()
     * @method UM_User_Bookmarks User_Bookmarks()
     * @method UM_Unsplash Unsplash()
     * @method UM_ForumWP ForumWP()
     * @method UM_Profile_Tabs Profile_Tabs()
     * @method UM_JobBoardWP JobBoardWP()
     * @method UM_Zapier Zapier()
     * @method UM_Stripe_API Stripe_API()
     * @method UM_Google_Authenticator Google_Authenticator()
     */
    final class UM extends \UM_Functions
    {
        /**
         * @var UM the single instance of the class
         */
        protected static $instance;
        /**
         * @var array all plugin's classes
         */
        public $classes = array();
        /**
         * @var bool Old variable
         *
         * @todo deprecate this variable
         */
        public $is_filtering;
        /**
         * WP Native permalinks turned on?
         *
         * @var
         */
        public $is_permalinks = \false;
        /**
         * @var null|string
         */
        public $honeypot = \null;
        /**
         * Main UM Instance
         *
         * Ensures only one instance of UM is loaded or can be loaded.
         *
         * @since 1.0
         * @static
         * @see UM()
         * @return UM - Main instance
         */
        public static function instance()
        {
        }
        /**
         * Create plugin classes - not sure if it needs!!!!!!!!!!!!!!!
         *
         * @since 1.0
         * @see UM()
         *
         * @param $name
         * @param array $params
         * @return mixed
         */
        public function __call($name, array $params)
        {
        }
        /**
         * Function for add classes to $this->classes
         * for run using UM()
         *
         * @since 2.0
         *
         * @param string $class_name
         * @param bool $instance
         */
        public function set_class($class_name, $instance = \false)
        {
        }
        /**
         * Cloning is forbidden.
         * @since 1.0
         */
        public function __clone()
        {
        }
        /**
         * Unserializing instances of this class is forbidden.
         * @since 1.0
         */
        public function __wakeup()
        {
        }
        /**
         * UM pseudo-constructor.
         *
         * @since 2.0.18
         */
        function _um_construct()
        {
        }
        /**
         * Fallback to avoid fatal errors for users who still have UM extensions compatible with UM 1.3.x and install UM >= 2.0 version before these extensions update.
         * Doing 1.3.x active extensions deactivate for properly running 2.0.x AJAX upgrades.
         */
        public function old_update_patch()
        {
        }
        /**
         * Autoload UM classes handler
         *
         * @since 2.0
         *
         * @param $class
         */
        function um__autoloader($class)
        {
        }
        /**
         * Plugin Activation
         *
         * @since 2.0
         */
        function activation()
        {
        }
        /**
         * Plugin Deactivation
         *
         * @since 2.3
         */
        public function deactivation()
        {
        }
        /**
         * Maybe need multisite activation process
         *
         * @since 2.1.7
         */
        function maybe_network_activation()
        {
        }
        /**
         * Single site plugin activation handler
         */
        function single_site_activation()
        {
        }
        /**
         *
         */
        function extensions_init()
        {
        }
        /**
         * Include required core files used in admin and on the frontend.
         *
         * @since 2.0
         *
         * @return void
         */
        public function includes()
        {
        }
        /**
         * @since 2.1.0
         *
         * @return um\core\Member_Directory()
         */
        function member_directory()
        {
        }
        /**
         * @since 2.6.1
         *
         * @return um\core\Blocks()
         */
        public function blocks()
        {
        }
        /**
         * Get extension API
         *
         * @since 2.0.34
         *
         * @param $slug
         *
         * @return um_ext\um_bbpress\Init
         */
        function extension($slug)
        {
        }
        /**
         * @param $class
         *
         * @return mixed
         */
        function call_class($class)
        {
        }
        /**
         * @since 2.6.8
         *
         * @return um\ajax\Init
         */
        public function ajax()
        {
        }
        /**
         * @since 2.0
         * @since 2.6.8 changed namespace and class content.
         *
         * @return um\common\Init
         */
        public function common()
        {
        }
        /**
         * @since 2.6.8
         *
         * @return um\frontend\Init
         */
        public function frontend()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\External_Integrations()
         */
        function external_integrations()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Options()
         */
        function options()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Plugin_Updater()
         */
        function plugin_updater()
        {
        }
        /**
         * @since 2.0.45
         * @return um\admin\core\Admin_Theme_Updater()
         */
        function theme_updater()
        {
        }
        /**
         * @since 2.0
         */
        function ajax_init()
        {
        }
        /**
         * @since 2.0.30
         */
        function admin_ajax_hooks()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\admin\Admin
         */
        public function admin()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\admin\core\Admin_Menu()
         */
        function admin_menu()
        {
        }
        /**
         * @since 2.0.26
         *
         * @return um\admin\core\Admin_Navmenu()
         */
        function admin_navmenu()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\admin\core\Admin_Settings()
         */
        function admin_settings()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\admin\core\Admin_Upgrade()
         */
        function admin_upgrade()
        {
        }
        /**
         * GDPR privacy policy
         *
         * @since 2.0.14
         *
         * @return bool|um\admin\core\Admin_GDPR()
         */
        function admin_gdpr()
        {
        }
        /**
         * GDPR privacy policy
         *
         * @since 2.0.14
         *
         * @return bool|um\core\GDPR()
         */
        function gdpr()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\admin\core\Admin_Columns()
         */
        function columns()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\admin\core\Admin_Metabox()
         */
        function metabox()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\admin\core\Admin_Builder()
         */
        function builder()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\admin\core\Admin_DragDrop()
         */
        function dragdrop()
        {
        }
        /**
         * @since 2.0
         *
         * @param bool|array $data
         * @return um\admin\core\Admin_Forms()
         */
        function admin_forms($data = \false)
        {
        }
        /**
         * @since 2.0
         *
         * @param bool|array $data
         * @return um\admin\core\Admin_Forms_Settings()
         */
        function admin_forms_settings($data = \false)
        {
        }
        /**
         * @since 2.0.34
         *
         * @return um\Extensions
         */
        function extensions()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\Dependencies
         */
        function dependencies()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\Config
         */
        function config()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Rewrite
         */
        function rewrite()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Setup
         */
        function setup()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\FontIcons
         */
        function fonticons()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Login
         */
        function login()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Register
         */
        function register()
        {
        }
        /**
         * @since 2.0
         * @todo Make it deprecated and review extensions.
         *
         * @return um\frontend\Enqueue
         */
        public function enqueue()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Shortcodes
         */
        function shortcodes()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Account
         */
        function account()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Password
         */
        function password()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Form
         */
        public function form()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Fields
         */
        function fields()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\User
         */
        function user()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Roles_Capabilities
         */
        function roles()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\User_posts
         */
        function user_posts()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Profile
         */
        function profile()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Query
         */
        function query()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Date_Time
         */
        function datetime()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Builtin
         */
        function builtin()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Files
         */
        public function files()
        {
        }
        /**
         * @since 2.0.21
         *
         * @return um\core\Uploader
         */
        function uploader()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Validation
         */
        function validation()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Access
         */
        function access()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Permalinks
         */
        function permalinks()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Mail
         */
        function mail()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Logout
         */
        function logout()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Cron
         */
        function cron()
        {
        }
        /**
         * @since 2.0
         *
         * @return um\core\Templates
         */
        function templates()
        {
        }
        /**
         * @since 2.0.44
         *
         * @return um\core\Multisite
         */
        function multisite()
        {
        }
        /**
         * Maybe include and init Action Scheduler.
         *
         * @since 2.9.0
         *
         * @return um\action_scheduler\Init
         */
        public function maybe_action_scheduler()
        {
        }
        /**
         * Checks if the new design is enabled.
         *
         * @return bool
         */
        public function is_new_ui()
        {
        }
        /**
         * Include files with hooked filters/actions
         *
         * @since 2.0
         */
        function init()
        {
        }
        /**
         * Init UM widgets
         *
         * @since 2.0
         */
        public function widgets_init()
        {
        }
        /**
         * @since 2.0
         * @deprecated 2.7.0
         *
         * @return um\admin\Enqueue
         */
        public function admin_enqueue()
        {
        }
        /**
         * @since 2.0
         * @deprecated 2.8.6
         *
         * @return um\frontend\Modal
         */
        public function modal()
        {
        }
        /**
         * Loading UM textdomain.
         *
         * Note: 'ultimate-member' is a default textdomain.
         *
         * @since 2.8.5 WordPress native functions are used to make this function clear.
         * @deprecated 2.9.2 Ref. https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/#Enhanced-support-for-only-using-PHP-translation-files
         */
        public function localize()
        {
        }
        /**
         * @since 2.0
         * @deprecated 2.1.0
         * @return um\core\Member_Directory | um\core\Member_Directory_Meta
         */
        public function members()
        {
        }
        /**
         * @since 2.0
         * @deprecated 2.9.2
         */
        public function mobile()
        {
        }
    }
}
namespace um\core {
    /**
     * Class Member_Directory
     * @package um\core
     */
    class Member_Directory
    {
        /**
         * Member Directory Views
         *
         * @var array
         */
        var $view_types = array();
        /**
         * @var array
         */
        var $sort_fields = array();
        /**
         * @var array
         */
        var $sort_data_types = array();
        /**
         * @var array
         */
        var $default_sorting = array();
        /**
         * @var array
         */
        var $filter_fields = array();
        /**
         * @var array
         */
        public $searching_fields = array();
        /**
         * @var array
         */
        var $custom_filters_in_query = array();
        var $filter_supported_fields = array();
        var $sorting_supported_fields = array();
        var $filter_types = array();
        /**
         * Fields used for searching from wp_users table.
         *
         * @var string[]
         */
        public static $core_search_fields = array('user_login', 'user_url', 'display_name', 'user_email', 'user_nicename');
        /**
         * Fields used for sorting from wp_users table.
         *
         * @var string[]
         */
        var $core_users_fields = array('user_login', 'user_url', 'display_name', 'user_email', 'user_nicename', 'user_registered');
        /**
         * @var
         */
        var $query_args;
        /**
         * @var User Card cover size
         */
        var $cover_size;
        /**
         * @var User Avatar size
         */
        var $avatar_size;
        /**
         * @var bool Searching marker
         */
        var $is_search = false;
        /**
         * Member_Directory constructor.
         */
        public function __construct()
        {
        }
        /**
         * Set member directory token as soon as it's created.
         *
         * @param int     $post_ID
         * @param \WP_Post $post
         * @param bool    $update
         *
         * @return void
         */
        public function set_token($post_ID, $post, $update)
        {
        }
        /**
         * Check if the user can view the member directory.
         *
         * @param int      $directory_id
         * @param int|null $user_id
         *
         * @return bool
         */
        public function can_view_directory($directory_id, $user_id = null)
        {
        }
        /**
         * Get the WordPress core searching fields in wp_users query.
         *
         * @since 2.6.10
         * @version 2.10.2
         * @param array|null  $qv     WP_User_Query variables.
         * @param string|null $search Search line value.
         * @return array
         */
        protected function get_core_search_fields($qv = null, $search = null)
        {
        }
        /**
         * @return bool
         */
        function get_hide_in_members_default()
        {
        }
        /**
         * Getting member directory post ID via hash.
         * Hash is unique attr, which we use visible at frontend
         *
         * @param string $hash
         *
         * @return bool|int
         */
        public function get_directory_by_hash($hash)
        {
        }
        /**
         * Generate a secure random token for each directory
         *
         * @param int $id
         *
         * @return false|string
         */
        public function set_directory_hash($id)
        {
        }
        /**
         * @param $id
         *
         * @return bool|string
         */
        public function get_directory_hash($id)
        {
        }
        /**
         * Generate a secure random token for each user card
         *
         * @param int $id
         *
         * @return false|string
         */
        public function set_user_hash($id)
        {
        }
        /**
         * @param $id
         *
         * @return bool|string
         */
        public function get_user_hash($id)
        {
        }
        /**
         * Get view Type template
         * @param string $type
         *
         * @return string
         */
        function get_type_basename($type)
        {
        }
        /**
         * Tag conversion for member directory
         *
         * @param string $string
         * @param array $array
         *
         * @return string
         */
        function convert_tags($string, $array)
        {
        }
        /**
         * Members page allowed?
         *
         * can be disabled by "Enable Members Directory" option
         *
         */
        public function access_members()
        {
        }
        /**
         * @param $value
         * @param $key
         * @param $post_id
         *
         * @return array
         */
        public function before_save_data($value, $key, $post_id)
        {
        }
        /**
         *
         */
        function init_variables()
        {
        }
        /**
         * Render member's directory
         * filters selectboxes
         *
         * @param string $filter
         * @param array $directory_data
         * @param mixed $default_value
         * @param bool $admin
         *
         * @return string $filter
         */
        public function show_filter($filter, $directory_data, $default_value = false, $admin = false)
        {
        }
        /**
         * @param string $filter
         * @param array $directory_data
         *
         * @return mixed
         */
        function slider_filters_range($filter, $directory_data)
        {
        }
        /**
         * Get the placeholders array for the slider-type filter.
         * Format `array( 'singular-placeholder', 'plural-placeholder' )`.
         *
         * @param string $filter
         * @param array  $attrs
         *
         * @return array
         */
        public function slider_range_placeholder($filter, $attrs)
        {
        }
        /**
         * @param $filter
         *
         * @return mixed
         */
        public function datepicker_filters_range($filter)
        {
        }
        /**
         * @param $filter
         *
         * @return mixed
         */
        protected function timepicker_filters_range($filter)
        {
        }
        /**
         * @param $borndate
         *
         * @return false|string
         */
        function borndate($borndate)
        {
        }
        /**
         * Handle members can view restrictions
         */
        function restriction_options()
        {
        }
        /**
         * Determine if the current user can edit other users
         *
         * @return bool Returns true if the current user can edit users, false otherwise
         */
        protected function can_edit_users()
        {
        }
        /**
         *
         */
        public function hide_not_approved()
        {
        }
        /**
         *
         */
        function hide_by_role()
        {
        }
        /**
         *
         */
        function hide_by_account_settings()
        {
        }
        /**
         * Handle "General Options" metabox settings
         *
         * @param array $directory_data
         */
        function general_options($directory_data)
        {
        }
        /**
         * Handle "User Roles to Display" option
         *
         * @param array $directory_data
         */
        function show_selected_roles($directory_data)
        {
        }
        /**
         * Handle "Only show members who have uploaded a profile photo" option
         *
         * @param array $directory_data
         */
        function show_only_with_avatar($directory_data)
        {
        }
        /**
         * Handle "Only show members who have uploaded a cover photo" option
         *
         * @param array $directory_data
         */
        function show_only_with_cover($directory_data)
        {
        }
        /**
         * Handle "Only show specific users (Enter one username per line)" option
         *
         * @param array $directory_data
         */
        function show_only_these_users($directory_data)
        {
        }
        /**
         * Handle "Exclude specific users (Enter one username per line)" option
         *
         * @param array $directory_data
         */
        function exclude_these_users($directory_data)
        {
        }
        /**
         * Handle "Pagination Options" metabox settings
         *
         * @param array $directory_data
         */
        function pagination_options($directory_data)
        {
        }
        /**
         * Add sorting attributes for \WP_Users_Query
         *
         * @param array $directory_data Member Directory options
         */
        public function sorting_query($directory_data)
        {
        }
        /**
         * Sorting random
         *
         * @param object $query
         *
         * @return mixed
         */
        function sortby_randomly($query)
        {
        }
        /**
         * Sorting by last login
         *
         * @param object $query
         *
         * @return mixed
         */
        public function sortby_last_login($query)
        {
        }
        /**
         * Prepare the search line. Avoid the using mySQL statement.
         *
         * @param string $search
         *
         * @return string
         */
        protected function prepare_search($search)
        {
        }
        /**
         * Handle general search line request
         */
        public function general_search()
        {
        }
        /**
         * Handle filters request
         */
        function filters($directory_data)
        {
        }
        /**
         * Set default filters
         *
         * @param $directory_data
         */
        public function default_filters($directory_data)
        {
        }
        /**
         * Get data array for pagination
         *
         *
         * @param array $directory_data
         * @param int $total_users
         *
         * @return array
         */
        function calculate_pagination($directory_data, $total_users)
        {
        }
        /**
         * @param int $user_id
         *
         * @return array
         */
        private function build_user_actions_list($user_id)
        {
        }
        /**
         * @param int $user_id
         * @param array $directory_data
         *
         * @return array
         */
        public function build_user_card_data($user_id, $directory_data)
        {
        }
        /**
         * Update limit query
         *
         * @param \WP_User_Query $user_query
         */
        public function pagination_changes($user_query)
        {
        }
        /**
         * Update search query
         *
         * @param \WP_User_Query $user_query
         *
         * @throws \Exception
         */
        public function search_changes($user_query)
        {
        }
        function predefined_no_caps($directory_data)
        {
        }
        /**
         * Main Query function for getting members via AJAX
         */
        public function ajax_get_members()
        {
        }
        /**
         * New menu
         *
         * @param string $element
         * @param string $trigger
         * @param array $items
         * @param string $parent
         */
        function dropdown_menu($element, $trigger, $items = array(), $parent = '')
        {
        }
        /**
         * New menu JS
         *
         * @param string $element
         * @param string $trigger
         * @param string $item
         * @param string $additional_attributes
         * @param string $parent
         */
        function dropdown_menu_js($element, $trigger, $item, $additional_attributes = '', $parent = '')
        {
        }
        /**
         * AJAX handler - Get options for the member directory "Admin filtering"
         * @version 2.1.12
         */
        function default_filter_settings()
        {
        }
        /**
         * Get member directory id by page id.
         *
         * @param int $page_id Page ID.
         *
         * @return array Member directories ID.
         */
        public function get_member_directory_id($page_id)
        {
        }
    }
    /**
     * Class Member_Directory_Meta
     * @package um\core
     */
    class Member_Directory_Meta extends \um\core\Member_Directory
    {
        /**
         * @var array
         */
        public $joins = array();
        /**
         * @var array
         */
        public $where_clauses = array();
        /**
         * @var array
         */
        public $roles = array();
        /**
         * @var bool
         */
        private $roles_in_query = false;
        /**
         * @var bool
         */
        public $general_meta_joined = false;
        /**
         * @var string
         */
        private $having = '';
        /**
         * @var string
         */
        private $select = '';
        /**
         * @var string
         */
        private $sql_limit = '';
        /**
         * @var string
         */
        public $sql_order = '';
        /**
         * Member_Directory_Meta constructor.
         */
        public function __construct()
        {
        }
        /**
         * Delete custom field and metakey from UM usermeta table
         *
         * @param $metakey
         * @param $args
         */
        public function on_delete_custom_field($metakey, $args)
        {
        }
        /**
         * Add metakey to usermeta fields
         *
         * @param $metakey
         * @param $args
         */
        public function on_new_field_added($metakey, $args)
        {
        }
        /**
         * When you delete usermeta - remove row from um_metadata
         *
         * @param int|array $meta_ids
         * @param int $object_id
         * @param string $meta_key
         * @param mixed $_meta_value
         */
        public function on_delete_usermeta($meta_ids, $object_id, $meta_key, $_meta_value)
        {
        }
        /**
         * When you add/update usermeta - add/update row from um_metadata
         *
         * @param int $meta_id
         * @param int $object_id
         * @param string $meta_key
         * @param mixed $_meta_value
         */
        public function on_update_usermeta($meta_id, $object_id, $meta_key, $_meta_value)
        {
        }
        /**
         * @param $directory_data
         * @param $field
         * @param $value
         * @param int  $i
         * @param bool $is_default
         */
        protected function handle_filter_query($directory_data, $field, $value, $i, $is_default = false)
        {
        }
        /**
         * Main Query function for getting members via AJAX
         */
        public function ajax_get_members()
        {
        }
    }
    /**
     * Class Query
     * @package um\core
     */
    class Query
    {
        /**
         * @var array
         */
        public $wp_pages = array();
        /**
         * @var array
         */
        public $roles = array();
        /**
         * Query constructor.
         */
        public function __construct()
        {
        }
        /**
         * Ajax pagination for posts
         */
        public function ajax_paginate()
        {
        }
        /**
         * Get wp pages
         *
         * @return array|string
         */
        public function wp_pages()
        {
        }
        /**
         * Get all forms
         *
         * @return mixed
         */
        public function forms()
        {
        }
        /**
         * Do custom queries
         *
         * @param array $args
         *
         * @return array|bool|int|\WP_Query
         */
        public function make($args)
        {
        }
        /**
         * Get last users
         *
         * @param int $number
         *
         * @return array
         */
        function get_recent_users($number = 5)
        {
        }
        /**
         * Count users by status
         *
         * @since 2.4.2 $status = 'unassigned' is unused. Please use `UM()->setup()->set_default_user_status()` instead. Will be deprecated since 3.0
         *
         * @param $status
         *
         * @return int
         */
        function count_users_by_status($status)
        {
        }
        /**
         * Get pending users (in queue)
         *
         * @return int
         */
        function get_pending_users_count()
        {
        }
        /**
         * Count all users
         *
         * @param bool $force Avoid transient. Default false.
         *
         * @return int
         */
        public function count_users($force = false)
        {
        }
        /**
         * Using wpdb instead of update_post_meta
         *
         * @param $key
         * @param $post_id
         * @param $new_value
         */
        function update_attr($key, $post_id, $new_value)
        {
        }
        /**
         * Get postmeta related to Ultimate Member.
         *
         * @param string $key
         * @param int    $post_id
         *
         * @return mixed
         */
        public function get_attr($key, $post_id)
        {
        }
        /**
         * Delete data
         *
         * @param $key
         * @param $post_id
         *
         * @return bool
         */
        function delete_attr($key, $post_id)
        {
        }
        /**
         * Checks if post has a specific meta key
         *
         * @param $key
         * @param null $value
         * @param null $post_id
         *
         * @return bool
         */
        function has_post_meta($key, $value = null, $post_id = null)
        {
        }
        /**
         * Get posts with specific meta key/value
         *
         * @param $post_type
         * @param $key
         * @param $value
         *
         * @return bool
         */
        function find_post_id($post_type, $key, $value)
        {
        }
        /**
         * Get post data
         *
         * @param int $post_id
         *
         * @return array
         */
        public function post_data($post_id)
        {
        }
        /**
         * Capture selected value
         *
         * @param string $key
         * @param string|null $array_key
         * @param bool $fallback
         * @return int|mixed|null|string
         */
        function get_meta_value($key, $array_key = null, $fallback = false)
        {
        }
        /**
         * Checks if its a core page of UM
         *
         * @param $post_id
         *
         * @return bool|mixed
         */
        function is_core($post_id)
        {
        }
        /**
         * Get users by status
         *
         * @param $status
         * @param int $number
         *
         * @deprecated 2.4.2
         *
         * @return array
         */
        function get_users_by_status($status, $number = 5)
        {
        }
    }
}
namespace {
    /**
     * Function for calling UM methods and variables
     *
     * @since 2.0
     *
     * @return UM
     */
    function UM()
    {
    }
    /**
     * Check if we are on a UM Core Page or not
     *
     * Default um core pages slugs
     * 'user', 'login', 'register', 'members', 'logout', 'account', 'password-reset'
     *
     * @param string $page UM core page slug
     *
     * @return bool
     */
    function um_is_core_page($page)
    {
    }
    /**
     * Gets the requested user
     *
     * @return bool|null
     */
    function um_get_requested_user()
    {
    }
    /**
     * Display a link to profile page
     *
     * @param int|null $user_id
     *
     * @return bool|string
     */
    function um_user_profile_url($user_id = \null)
    {
    }
    /**
     * Default avatar URL
     *
     * @return string
     */
    function um_get_default_avatar_uri()
    {
    }
}
