<?php

/**
 * wpbakery 8.7.4
 * Generated by tests/bin/generate-stubs.php — do not edit, rerun `make stubs`.
 * Source: tests/bin/zips/js_composer.zip
 */

namespace {
    \define('WPB_VC_VERSION', '8.7.4');
}
namespace {
    /**
     * Class WPBakeryShortCode
     */
    abstract class WPBakeryShortCode
    {
        /**
         * Configurations for the shortcode.
         *
         * @var array
         */
        public static $config;
        /**
         * CSS settings for controls.
         *
         * @var string
         */
        protected $controls_css_settings = 'cc';
        /**
         * Backend section controls.
         *
         * @note For frontend editor section controls, please see
         * include/templates/editors/partials/frontend_controls.tpl.php
         *
         * @var array
         */
        protected $controls_list = ['edit', 'clone', 'copy', 'delete'];
        /**
         * Content of the shortcode.
         *
         * @var string
         */
        protected $shortcode_content = '';
        /**
         * Tag for the shortcode.
         *
         * @var string
         */
        protected $shortcode;
        /**
         * HTML template for rendering the shortcode.
         *
         * @var string
         */
        protected $html_template;
        /**
         * Shortcode attributes.
         *
         * @var array
         */
        protected $atts;
        /**
         * Shortcode settings.
         *
         * @var array
         */
        protected $settings;
        /**
         * JavaScript scripts associated with the shortcode.
         *
         * @var array
         */
        protected static $js_scripts = [];
        /**
         * CSS scripts associated with the shortcode.
         *
         * @var array
         */
        protected static $css_scripts = [];
        /**
         * Flag to check if default scripts have been enqueued.
         *
         * @var bool
         * @since 4.4.3
         */
        protected static $default_scripts_enqueued = \false;
        /**
         * String representation of the shortcode.
         *
         * @var string
         */
        protected $shortcode_string = '';
        /**
         * Path to the template file for rendering controls.
         *
         * @var string
         */
        protected $controls_template_file = 'editors/partials/backend_controls.tpl.php';
        /**
         * CSS class for non-draggable elements.
         *
         * @var string
         */
        public $nonDraggableClass = 'vc-non-draggable';
        /**
         * Constructor.
         *
         * @param array $settings
         */
        public function __construct($settings)
        {
        }
        /**
         * Initialize.
         *
         * @param array $settings
         * @deprecated not used
         */
        public function init($settings)
        {
        }
        /**
         * Add action.
         *
         * @param string $action
         * @param string $method
         * @param int $priority
         * @return true|void
         * @deprecated 6.0 use native WordPress actions
         */
        public function addAction($action, $method, $priority = 10)
        {
        }
        /**
         * Remove action.
         *
         * @param string $action
         * @param string $method
         * @param int $priority
         *
         * @return bool
         * @deprecated 6.0 use native WordPress actions
         */
        public function removeAction($action, $method, $priority = 10)
        {
        }
        /**
         * Add filter.
         *
         * @param string $filter
         * @param string $method
         * @param int $priority
         *
         * @return bool|void
         * @deprecated 6.0 use native WordPress actions
         */
        public function addFilter($filter, $method, $priority = 10)
        {
        }
        /**
         * Remove filter.
         *
         * @param string $filter
         * @param string $method
         * @param int $priority
         * @return bool
         * @deprecated 6.0 use native WordPress
         */
        public function removeFilter($filter, $method, $priority = 10)
        {
        }
        /**
         * Add shortcode.
         *
         * @param string $tag
         * @param string $func
         * @deprecated 6.0 not used
         */
        public function addShortCode($tag, $func)
        {
        }
        /**
         * Execute shortcode.
         *
         * @param string $content
         * @deprecated 6.0 not used
         */
        public function doShortCode($content)
        {
        }
        /**
         * Remove shortcode.
         *
         * @param string $tag
         * @deprecated 6.0 not used
         */
        public function removeShortCode($tag)
        {
        }
        /**
         * Post param.
         *
         * @param string $param
         *
         * @return null
         * @deprecated 6.0 not used, use vc_post_param
         */
        public function post($param)
        {
        }
        /**
         * Get param.
         *
         * @param string $param
         *
         * @return null
         * @deprecated 6.0 not used, use vc_get_param
         */
        public function get($param)
        {
        }
        /**
         * Assets url.
         *
         * @param string $asset
         *
         * @return string
         * @deprecated 4.5 use vc_asset_url
         */
        public function assetURL($asset)
        {
        }
        /**
         * Assets path.
         *
         * @param string $asset
         *
         * @return string
         * @deprecated 6.0 not used
         */
        public function assetPath($asset)
        {
        }
        /**
         * Config.
         *
         * @param string $name
         *
         * @return null
         * @deprecated 6.0 not used
         */
        public static function config($name)
        {
        }
        /**
         * Get inline anchor.
         *
         * @param string $content
         *
         * @return string
         */
        public function addInlineAnchors($content)
        {
        }
        /**
         * Enqueue assets.
         */
        public function enqueueAssets()
        {
        }
        /**
         * Prints out the styles needed to render the element icon for the back end interface.
         * Only performed if the 'icon' setting is a valid URL.
         *
         * @since  4.2
         * @return void
         */
        public function printIconStyles()
        {
        }
        /**
         * Register js.
         *
         * @param mixed $param
         */
        protected function registerJs($param)
        {
        }
        /**
         * Register css.
         *
         * @param mixed $param
         */
        protected function registerCss($param)
        {
        }
        /**
         * Enqueue css.
         */
        public static function enqueueCss()
        {
        }
        /**
         * Enqueue js.
         */
        public static function enqueueJs()
        {
        }
        /**
         * Get shortcode.
         *
         * @param string $shortcode
         */
        public function shortcode($shortcode)
        {
        }
        /**
         * Set shortcode template.
         *
         * @see include/templates
         * @param mixed $template
         *
         * @return string
         */
        protected function setTemplate($template)
        {
        }
        /**
         * Get shortcode template.
         *
         * @see include/templates
         * @return bool
         */
        protected function getTemplate()
        {
        }
        /**
         * Get name.
         *
         * @return mixed
         */
        protected function getFileName()
        {
        }
        /**
         * Find html template for shortcode output.
         */
        protected function findShortcodeTemplate()
        {
        }
        /**
         * Get shortcode content.
         *
         * @param array $atts
         * @param null $content
         *
         * @return mixed
         * @throws \Exception
         */
        protected function content($atts, $content = \null)
        {
        }
        /**
         * Get shortcode output.
         *
         * @param array $atts
         * @param null $content
         *
         * @see vc_filter: vc_shortcode_content_filter - hook to edit template content
         * @see vc_filter: vc_shortcode_content_filter_after - hook after template is loaded to override output
         *
         * @return mixed
         * @throws \Exception
         */
        protected function loadTemplate($atts, $content = \null)
        {
        }
        /**
         * Get admin output.
         *
         * @param array $atts
         * @param string $content
         *
         * @return string
         * @throws \Exception
         */
        public function contentAdmin($atts, $content = \null)
        {
        }
        /**
         * Check if admin.
         *
         * @return bool
         */
        public function isAdmin()
        {
        }
        /**
         * Check if inline.
         *
         * @return bool
         */
        public function isInline()
        {
        }
        /**
         * Check if editor.
         *
         * @return bool
         */
        public function isEditor()
        {
        }
        /**
         * Get shortcode output.
         *
         * @param array $atts
         * @param null $content
         * @param string $base
         *
         * vc_filter: vc_shortcode_output - hook to override output of shortcode
         *
         * @return string
         * @throws \Exception
         */
        public function output($atts, $content = \null, $base = '')
        {
        }
        /**
         * Enqueue default scripts.
         */
        public function enqueueDefaultScripts()
        {
        }
        /**
         * Return shortcode attributes, see \WPBakeryShortCode::output
         *
         * @return array
         * @since 4.4
         */
        public function getAtts()
        {
        }
        /**
         * Creates html before shortcode html.
         *
         * @param array $atts - shortcode attributes list.
         * @param string $content - shortcode content.
         *
         * @return string - html which will be displayed before shortcode html.
         */
        public function beforeShortcode($atts, $content)
        {
        }
        /**
         * Creates html before shortcode html.
         *
         * @param array $atts - shortcode attributes list.
         * @param string $content - shortcode content.
         *
         * @return string - html which will be displayed after shortcode html.
         */
        public function afterShortcode($atts, $content)
        {
        }
        /**
         * Add element class.
         *
         * @param string $el_class
         *
         * @return string
         */
        public function getExtraClass($el_class)
        {
        }
        /**
         * Add css animation.
         *
         * @param string $css_animation
         *
         * @return string
         */
        public function getCSSAnimation($css_animation)
        {
        }
        /**
         * Create HTML comment for blocks only if wpb_debug=true
         *
         * @param string $initial
         *
         * @return string
         * @deprecated 4.7 For debug type html comments use more generic debugComment function.
         */
        public function endBlockComment($initial)
        {
        }
        /**
         * If wpb_debug=true return HTML comment
         *
         * @param string $comment
         *
         * @return string
         * @since 4.7
         * @deprecated 5.5 no need for extra info in output, use xdebug
         */
        public function debugComment($comment)
        {
        }
        /**
         * Get specific settings.
         *
         * @param string $name
         *
         * @return string|null
         */
        public function settings($name)
        {
        }
        /**
         * Set settings.
         *
         * @param string $name
         * @param mixed $value
         */
        public function setSettings($name, $value)
        {
        }
        /**
         * Get all settings.
         *
         * @return mixed
         * @since 5.5
         */
        public function getSettings()
        {
        }
        /**
         * Get shortcode element holder.
         *
         * @param string $width
         *
         * @return string
         * @throws \Exception
         */
        public function getElementHolder($width)
        {
        }
        /**
         * Return block controls.
         *
         * @param string $controls
         * @param string $extended_css
         *
         * @return string
         * @throws \Exception
         */
        public function getColumnControls($controls, $extended_css = '')
        {
        }
        /**
         * Return list of controls.
         *
         * @return array
         * @throws \Exception
         */
        public function getControlsList()
        {
        }
        /**
         * Build new modern controls for shortcode.
         *
         * @param string $extended_css
         *
         * @return string
         * @throws \Exception
         */
        public function getColumnControlsModular($extended_css = '')
        {
        }
        /**
         * Add control classes.
         *
         * @return string
         * @throws \Exception
         */
        public function getBackendEditorControlsElementCssClass()
        {
        }
        /**
         * This will fire callbacks if they are defined in map.php
         *
         * @param string $id
         *
         * @return string
         */
        public function getCallbacks($id = '')
        {
        }
        /**
         * Add params html holders.
         *
         * @param array $param
         * @param string $value
         *
         * vc_filter: vc_wpbakeryshortcode_single_param_html_holder_value - hook to override param value (param type and etc is available in args)
         *
         * @return string
         */
        public function singleParamHtmlHolder($param, $value)
        {
        }
        /**
         * Retrieve icon.
         *
         * @param array $params
         *
         * @return string
         */
        protected function getIcon($params)
        {
        }
        /**
         * Get title.
         *
         * @param string $title
         *
         * @return string
         */
        protected function outputTitle($title)
        {
        }
        /**
         * Get template.
         *
         * @param string $content
         *
         * @return string
         * @throws \Exception
         */
        public function template($content = '')
        {
        }
        /**
         * This functions prepares attributes to use in template.
         * Converts back escaped characters.
         *
         * @param array $atts
         *
         * @return array
         */
        protected function prepareAtts($atts)
        {
        }
        /**
         * Get shortcode.
         *
         * @return string
         */
        public function getShortcode()
        {
        }
        /**
         * Get custom markup.
         *
         * Possible placeholders:
         *      {{ content }}
         *      {{ title }}
         *      {{ container-class }}
         *
         * Possible keys:
         *  {{
         *  <%
         *  %
         *
         * @param string $markup
         * @param string $content
         *
         * @return string
         * @throws \Exception
         * @since 4.5
         */
        protected function customMarkup($markup, $content = '')
        {
        }
        /**
         * Get params html holders.
         *
         * @param array $atts
         *
         * @return string
         */
        protected function paramsHtmlHolders($atts)
        {
        }
        /**
         * Check is allowed to add another element inside current element.
         *
         * @return bool
         * @since 4.8
         */
        public function getAddAllowed()
        {
        }
    }
    /**
     * Add your shortcode to the WPBakery elements list.
     *
     * @param array $attributes
     *
     * @return bool
     * @throws Exception
     * @since 4.2
     */
    function vc_map($attributes)
    {
    }
    /**
     * Helper function to create new element param type.
     *
     * @see https://kb.wpbakery.com/docs/developers-how-tos/create-new-param-type
     *
     * @param string $name - attribute name.
     * @param callable $form_field_callback - Callback will be called when settings form is shown and attribute added to shortcode
     *     param list.
     * @param string $script_url - javascript file url which will be attached at the end of settings form.
     *
     * @return bool
     * @since 4.4
     */
    function vc_add_shortcode_param($name, $form_field_callback, $script_url = \null)
    {
    }
}
